import 'package:bukin_app/models/book-model.dart';

final bookList = [
  BookModel(
      1,
      'Psicológicamente hablando',
      2016,
      'Adrián Triglia',
      53,
      105,
      true,
      'https://pymstatic.com/3900/conversions/psicologicamente-hablando-default.jpg',
      'Muchas personas nos escriben semanalmente para preguntarnos cuál es la mejor guía básica para aprender psicología. Este libro pretende cubrir esta necesidad. Psicológicamente hablando (Ediciones Paidós) es un manual para conocer los aspectos fundamentales de la ciencia de la conducta. '),
  BookModel(
      2,
      'Historia de dos ciudades',
      1859,
      'Charles Dickens',
      120,
      261,
      false,
      'https://pymstatic.com/1753/conversions/historia-dos-ciudades-default.jpg',
      'Esta novela del escritor británico Charles Dickens ha vendido más de 200 millones de copias. La novela se sitúa en la época de la Revolución Francesa, entre dos ciudades: Londres y París. El autor es muy crítico con las instituciones del victorianismo, aunque la novela se aleja de cualquier debate político o filosófico sobre la revolución debido a la indiferencia y el desprecio hacia los políticos por parte del autor.'),
  BookModel(
      3,
      '7 hábitos de la gente altamente efectiva',
      1989,
      'Stephen R. Covey',
      36,
      88,
      false,
      'https://www.leadersummaries.com/images-resumenes/los-7-habitos-de-la-gente-altamente-efectiva.jpg',
      'Este libro de Stephen R. Covey es una de las referencias del mundo empresarial. En sus hojas se repasan las costumbres más destacadas de las personas que resultan altamente efectivas en su día a día.'),
  BookModel(
      4,
      'Guerra y Paz',
      1869,
      'León Tolstói',
      251,
      1059,
      true,
      'https://pymstatic.com/1754/conversions/guerra-paz-default.jpg',
      'Esta novela del escritor ruso León Tolstói es un clásico de la literatura universal. Su texto narra las vidas de los miembros de distintas familias aristocráticas de la Rusia de entre 1805 y 1815, en el momento de las guerras napoleónicas. Alterna la descripción de dichas vidas con batallas como las de Austerlitz.'),
  BookModel(
      5,
      'La insoportable levedad del ser',
      1984,
      'Milan Kudera',
      12,
      53,
      true,
      'https://pymstatic.com/1756/conversions/la-insoportable-levedad-default.jpg',
      'La insoportable levedad del ser, de Milan Kundera, es una historia de amor, traiciones, celos y paradojas de la vida diaria de las parejas. Esta apasionante novela está tan bien explicada que el lector se acabará sintiendo parte de la historia. Un libro altamente recomendable.'),
];